const languages = {
    ENGLISH: {
      language: "English",
      loginheader: "Login to your account",
      loginSubHeader: "Complete setup by logging in with your new password & stay updated",
      userId: "User Id/ Email Id/ mobile No/ SR No",
      password: "Password",
      resetPassword: "Reset Password",
      forgotPassword: "Forgot Password",
      captcha: "Please verify the captcha",
      continue: "Continue",
      resetLoginHeader: "Reset Your Password",
      resetLoginSubHeader: "Please reset your password to stay connected and secured",
      oldPassword: "Old password",
      otpVerification: "Verify with OTP",
      otpShared: "Please Complete OTP verification shared on your mobile",
      otp: "OTP",
      otpSubHeader: "Please Complete OTP verification to reset your password",
      resendOtp: "Resend OTP",
      verifyOtp: "Verify OTP",
      resetPasswordheader: "Reset Your Password",
      setupPasswordHeader: "Setup Your Password",
      resetPasswordSubheader: "Please reset your password to stay connected and secured",
      capchaHuman: "Are You a human",
      proceed: "Proceed",
      newPasswordSubheader: "Stay secured, setup a strong password for your LIC account",
      newPassword: "New password",
      confirmPassword: "Confirm new password",
      confirm: "Confirm",
      movheader: "Merchant OTP Verification",
      movSubHeader: "Please Complete OTP verification for the shared on the merchants mobile number",
      authenticationHeader: "2 factor authentication",
      authenticationSubHeader: " Please complete 2FA verification for secure login to your LIC account",
      googlePlaceHolder: "Please Enter Google Auth Code",
      verify: "Verify",
      loginOTP: "Login using OTP",
      newPasswordheader: "Set New Password",
      licHeader: "Welcome to LIC family",
      licSubHeader: "Please complete one time setup to access your LIC account.",
      // Validation messages
      passwordRequired: "Password is required",
      minPasswordRequired: "Password should be minimum 5 characters",
      maxPasswordRequired: "Password should be maximum 10 characters",
      validPasswordRequired: "Password must contain a combination of alphanumeric characters",
      oldPasswordRequired: "Old password is required",
      confirmPasswordRequired: "Confirm password is required",
      passwordsMatch: "Passwords must match",
      otpRequired: "OTP is required",
      merchantOTPRequired: "Merchant OTP is required.",
      authCodeRequired: "Auth Code is required.",
      googleAuthCodeRequired: "Google Auth Code is required.",
      emailRequired: "User Id/Email ID/Mobile No/SR No is required",
      userIDRequired: "User ID is required.",
      gAuth: "Google authenticator",
      twoFactorAuthHeading: "Enable 2 factor authentication",
      twoFactorAuthSubHeading: "Configuring google authenticator",
      pointOne: "Install google authenticator (iOS-Android).",
      pointTwo: "In the authenticator app, select '+' icon.",
      pointThree: "Select “Scan a barcode (or QR code)” to scan this barcode.",
      scanQRCode: "Scan QR Code",
      verifyCode: "Verify Code",
      settingMessage: "For changing the setting, please verify the authentication code:",
      verifyAndActivate: "Verify and Activate",
      loginSubHeading: "Use your user ID & password to login and access LIC account"
  },
    HINDI: {
      language: "Hindi",
      loginheader: "अपने खाते में लॉगिन करें",
      loginSubHeader: "नए पासवर्ड से लॉगिन करके सेटअप पूरा करें और अपडेट रहें",
      userId: "यूजर आईडी/ ईमेल आईडी/ मोबाइल नंबर/ एसआर नंबर",
      password: "पासवर्ड",
      resetPassword: "पासवर्ड रीसेट करें",
      forgotPassword: "पासवर्ड भूल गए",
      captcha: "कृपया कैप्चा सत्यापित करें",
      continue: "जारी रखें",
      resetLoginHeader: "अपना पासवर्ड रीसेट करें",
      resetLoginSubHeader: "सुरक्षित रहने के लिए कृपया अपना पासवर्ड रीसेट करें",
      oldPassword: "पुराना पासवर्ड",
      otpVerification: "ओटीपी के साथ सत्यापित करें",
      otpShared: "कृपया अपने मोबाइल पर साझा की गई ओटीपी सत्यापन पूरा करें",
      otp: "ओटीपी",
      otpSubHeader: "कृपया अपना पासवर्ड रीसेट करने के लिए ओटीपी सत्यापन पूरा करें",
      resendOtp: "ओटीपी पुनः भेजें",
      verifyOtp: "ओटीपी सत्यापित करें",
      resetPasswordheader: "अपना पासवर्ड रीसेट करें",
      setupPasswordHeader: "अपना पासवर्ड सेटअप करें",
      resetPasswordSubheader: "सुरक्षित रहने के लिए कृपया अपना पासवर्ड रीसेट करें",
      capchaHuman: "क्या आप मानव हैं",
      proceed: "आगे बढ़ें",
      newPasswordSubheader: "सुरक्षित रहें, अपने एलआईसी खाते के लिए मजबूत पासवर्ड सेटअप करें",
      newPassword: "नया पासवर्ड",
      confirmPassword: "नया पासवर्ड पुष्टि करें",
      confirm: "पुष्टि करें",
      movheader: "विक्रेता ओटीपी सत्यापन",
      movSubHeader: "कृपया विक्रेता के मोबाइल नंबर पर साझा की गई ओटीपी सत्यापन पूरा करें",
      authenticationHeader: "2 चरणीय प्रमाणीकरण",
      authenticationSubHeader: "अपने एलआईसी खाते में सुरक्षित लॉगिन के लिए कृपया 2एफए सत्यापन पूरा करें",
      googlePlaceHolder: "कृपया गूगल ऑथ कोड दर्ज करें",
      verify: "सत्यापित करें",
      loginOTP: "ओटीपी का उपयोग करके लॉगिन करें",
      newPasswordheader: "नया पासवर्ड सेट करें",
      licHeader: "एलआईसी परिवार में आपका स्वागत है",
      licSubHeader: "अपने एलआईसी खाते तक पहुंच प्राप्त करने के लिए कृपया एक बार सेटअप पूरा करें।",
      // Validation messages
      passwordRequired: "पासवर्ड आवश्यक है",
      minPasswordRequired: "पासवर्ड न्यूनतम 5 अक्षर होना चाहिए",
      maxPasswordRequired: "पासवर्ड अधिकतम 10 अक्षर होना चाहिए",
      validPasswordRequired: "पासवर्ड में अल्फ़ान्यूमेरिक वर्णों का संयोजन होना चाहिए",
      oldPasswordRequired: "पुराना पासवर्ड आवश्यक है",
      confirmPasswordRequired: "पासवर्ड पुष्टि आवश्यक है",
      passwordsMatch: "पासवर्ड मेल खाना चाहिए",
      otpRequired: "ओटीपी आवश्यक है",
      merchantOTPRequired: "विक्रेता ओटीपी आवश्यक है।",
      authCodeRequired: "ऑथ कोड आवश्यक है।",
      googleAuthCodeRequired: "गूगल ऑथ कोड आवश्यक है।",
      emailRequired: "यूजर आईडी/ईमेल आईडी/मोबाइल नंबर/एसआर नंबर आवश्यक है",
      userIDRequired: "यूजर आईडी आवश्यक है।",
      gAuth: "गूगल ऑथेंटिकेटर",
      twoFactorAuthHeading: "2 चरणीय प्रमाणीकरण सक्षम करें",
      twoFactorAuthSubHeading: "गूगल ऑथेंटिकेटर कॉन्फ़िगर करें",
      pointOne: "गूगल ऑथेंटिकेटर इंस्टॉल करें (आईओएस-एंड्रॉइड)।",
      pointTwo: "ऑथेंटिकेटर ऐप में, '+' आइकन चुनें।",
      pointThree: "इस बारकोड (या क्यूआर कोड) को स्कैन करने के लिए “बारकोड (या क्यूआर कोड) स्कैन करें” चुनें।",
      scanQRCode: "क्यूआर कोड स्कैन करें",
      verifyCode: "कोड सत्यापित करें",
      settingMessage: "सेटिंग बदलने के लिए, कृपया ऑथेंटिकेशन कोड सत्यापित करें:",
      verifyAndActivate: "सत्यापित करें और सक्रिय करें",
      loginSubHeading: "एलआईसी खाते में लॉगिन और पहुंच प्राप्त करने के लिए अपने यूजर आईडी और पासवर्ड का उपयोग करें"
  }
};